### PR TITLE
Refactor time-series-momentum.Rmd

### PR DESCRIPTION
**Pull request by JiaruiWang-Jill**
I finished refactor of time-series-momentum.rmd.

### CODE REVIEW

**Comment by JustinMShea** [comment]
Thanks for the PR @JiaruiWang-Jill! Please recommit this and change the file name back to its original, so we can see the `diff` and view the changes you made more easily. Also, did you see our prompts in the channel slack? Please login and respond there. Thanks!

**Review by JiaruiWang-Jill — COMMENTED** [review]
Update. I finished file time-series-momentum.rmd. I didn't work on value-momentum-everywhere.rmd.

**Comment by JustinMShea** [comment]
HI @JiaruiWang-Jill Thanks for the commit, sure we will take a look. We've been prompting you on slack to setup a meeting to answer questions for over a week. Do the time ranges you listed still work for your? If not, let us know what works. When would you be available to go over the work and plan the steps necessary to get caught up prior to the coming evaluation period on July 12-16th? Thanks so much.

**Comment by JiaruiWang-Jill** [comment]
Hi Justin,

Yeah yeah. The times lot I provided still works for me.

I thought I was waiting for the update of your available meeting time.
Sorry for causing the misunderstanding. When will be a good time for you?

Jiarui

**Comment by JustinMShea** [comment]
Ok great. Lets meet Saturday 9 am HKT (Friday 8 pm CST)! I'll send a zoom link via email

**Review by JiaruiWang-Jill — COMMENTED** [review]
I solved this problem by switching factors.name and asstes.name.

**Pull request merged**
